spring:
  application:
    name: Merchants
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: bd1998
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

#logging:
#  level: debug
#  file: merchants.log
